include colors.conf

window_margin_width 10.0

confirm_os_window_close 0

font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font
italic_font      FiraCode Nerd Font
bold_italic_font FiraCode Nerd Font
font_size 11
adjust_line_height 5
scrollback_indicator_display on_scroll
scrollback_indicator_opacity 0.1	
shell /usr/bin/fish
scrollbar_width 0
