#  _   _                 ___    _ _      
# | | | |_   _ _ __  _ _|_ _|__| | | ___ 
# | |_| | | | | '_ \| '__| |/ _` | |/ _ \
# |  _  | |_| | |_) | |  | | (_| | |  __/
# |_| |_|\__, | .__/|_| |___\__,_|_|\___|
#        |___/|_|                        

general {
    # Mantém o hyprlock (funciona perfeitamente no Niri)
    lock_cmd = pidof hyprlock || hyprlock
    
    # Bloqueia a sessão antes do sistema suspender
    before_sleep_cmd = loginctl lock-session
    
    # Garante que as telas liguem ao acordar da suspensão
    after_sleep_cmd = niri msg action power-on-monitors
}

listener {
    # 1.5 minutos para bloquear a tela
    timeout = 90
    on-timeout = loginctl lock-session
}

listener {
    # 2 minutos para desligar os monitores usando o comando nativo do Niri
    timeout = 120
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
