# Rose Pine
# Theme create by: https://github.com/pearcidar
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "rose-pine"

# ========= Border =========
file_panel_border = "#908caa"
sidebar_border = "#908caa"
footer_border = "#908caa"

# ========= Border Active =========
file_panel_border_active = "#ebbcba"
sidebar_border_active = "#ebbcba"
footer_border_active = "#ebbcba"
modal_border_active = "#ebbcba"

# ========= Background (bg) =========
full_screen_bg = "#191724"
file_panel_bg = "#191724"
sidebar_bg = "#191724"
footer_bg = "#191724"
modal_bg = "#191724"

# ========= Foreground (fg) =========
full_screen_fg = "#e0def4"
file_panel_fg = "#e0def4"
sidebar_fg = "#e0def4"
footer_fg = "#e0def4"
modal_fg = "#e0def4"

# ========= Special Color =========
cursor = "#9ccfd8"
correct = "#8ec07c"
error = "#ff6969"
hint = "#31784f"
cancel = "#838383"
# Gradient color can only have two color!
gradient_color = ["#31784f", "#eb6f92"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#9ccfd8"
file_panel_top_path = "#ebbcba"
file_panel_item_selected_fg = "#c4a7e7"
file_panel_item_selected_bg = "#191724"

# ========= Sidebar Special Items =========
sidebar_title = "#6e6e86"
sidebar_item_selected_fg = "#f6c177"
sidebar_item_selected_bg = "#191724"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#e0def4"
modal_cancel_bg = "#524f67"

modal_confirm_fg = "#e0def4"
modal_confirm_bg = "#eb6f92"

# ========= Help Menu =========
help_menu_hotkey = "#f6c177"
help_menu_title = "#9ccfd8"
